version: 2
updates:
  # Python (Backend)
  - package-ecosystem: pip
    directory: /Backend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - backend

  # npm (Frontend)
  - package-ecosystem: npm
    directory: /Frontend/nimrag-frontend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - frontend

  # GitHub Actions selbst
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
