version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - DATABASE_URL=sqlite+aiosqlite:///./data.db
    volumes:
      - ./app:/app/app:cached

  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
